### ISSUE TITLE
SafeRepresentorAgent transitions are broken

### ISSUE THREAD

**Issue by csavage-mdsol** [mdsol/farscape#29]
It looks like transitions are trying to be dispatched to a string, which would imply the representor in a SafeRepresentorAgent and a RepresentorAgent is a string and not a representor.  Basically it looks like reframe_representor has a bug.  Repro steps:

bundle exec pry

```
require 'moya'
require 'farscape'
@pid = Moya.spawn_rails_process!
door = Farscape::Agent.new("http://localhost:3000")
drds = door.enter.drds
drds.safe.transitions #=> NoMethodError
drds.unsafe.transitions # => NoMethodError: undefined method `transitions' for #<String:0x007f86e79e2468>
from /Users/csavage/Desktop/farscape/lib/farscape/representor.rb:25:in `transitions'

```

**Comment by sheavalentine-mdsol** [comment]
https://github.com/mdsol/farscape/pull/30

**Comment by sheavalentine-mdsol** [comment]
@csavage-mdsol - is this addressed satisfactorily?

**Comment by csavage-mdsol** [comment]
Yup, closing
