### ISSUE TITLE
Content negotiation

### ISSUE THREAD

**Issue by csavage-mdsol** [mdsol/farscape#31]
Content negotiation is currently insufficient for changing types in the middle of a series of requests.  Notable immediate use cases are things like "help" and "profile" links.  We currently present them as valid transitions, and raise a variety of unfun errors when you attempt to invoke them.

I think we should raise better errors soonish, and in the long term handle content negotiation intelligently, possibly automatically retrying 406s or some such.

@HonoreDB @sheavalentine-mdsol

**Comment by sheavalentine-mdsol** [comment]
It seems to be that there's a few things going on here.

API's should be publishing the 'enctype' of the request.  Though obviously we need to handle that smartly.
While the hale spec says that the default enctype is 'application/hale+json', Farscape should be smarter than the request.  So:

```
If enctype is known
  make request with that enctype
else
  make request as current enctype
  if an unexpected media type is returned
    look for known enctype in Accept header
    if known enctype is found
      make request with that enctype
    else if text/* is found
      make a Representor with only 'doc' populated
    else
      Error
    end
  end
end

```
