### ISSUE TITLE
Use discovery service

### ISSUE THREAD

**Issue by jcarres-mdsol** [mdsol/farscape#32]
Farscape will be much more useful if it is already hooked up with a discovery service. 
maybe something like .discover('resource_name') would go to the service, get the URL of the resource_name's billboard URL, follow it and return the representation of the contents of that URL.

**Comment by fosrias** [comment]
This was the point of the #enter method in my pseudo code way back when. That is allowed resolving through a discovery service if configured. So :+1: on some method, whatever it is called that transparently works with a discovery service. Wormhole should work well for this as that was the guiding idea behind its design. That Farscape would point at it to enter resources.

**Comment by HonoreDB** [comment]
We're about to write a plugin to do this with wormhole.

**Comment by fosrias** [comment]
Cool.
