### ISSUE TITLE
README full of errors

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [mdsol/farscape#50]
- Crichton is not open source so all the links pointing to it (in the README as well as in the CONTRIBUTING page) are 404 for non mdsol people.
- The "Checkout the Documentation for more info." link is a 404.
- The "This method returns a Farscape::Representor instance" link is a 404.
- LICENSE area & file say copyright **2013**...

Since I'm not so familiar with this gem I can't simply do a PR and fix these, wouldn't know where the links should point to etc.
@jcarres-mdsol thoughts?

**Comment by fosrias** [comment]
@jfeltesse-mdsol There is a shared version of [Crichton](https://github.com/mdsol-share/crichton), but I am not sure that it is very current compared to the internal version.

**Comment by jfeltesse-mdsol** [comment]
@fosrias thanks for the heads up. At the very least the links should be pointing there then.

**Comment by jfeltesse-mdsol** [comment]
it's been 6 months, I guess it's time to close since it's pretty obvious this won't get addressed anytime soon.
